language: node_js
node_js:
  - "12"
services:
  - postgresql
addons:
  - postgresql: "10"
before_script:
  - psql -U postgres -c 'create database budget_test;'
  - psql -U postgres budget_test -c 'create extension if not exists "uuid-ossp"'
env:
  global:
    - POSTGRES_USER: docker
    - POSTGRES_PASSWORD: docker
    - DATABASE_URL: postgres://postgres:postgres@localhost:5432/budget_test
