version: "2"
services:
  budget_test:
    container_name: budget_test
    build:
      context: .
      dockerfile: test.Dockerfile
    links:
      - db_test:db_test
    networks:
      - net_budget_test
    environment:
      NODE_ENV: test
      PORT: 3000
      DATABASE_URL: postgres://docker:docker@db_test:5432/budget
      DEFAULT_PIN: 1234
    command: "true"
  db_test:
    restart: always
    image: postgres:latest
    networks:
      - net_budget_test
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
networks:
  net_budget_test:
    driver: bridge
