version: "2"
services:
  budget:
    container_name: budget
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    links:
      - db:db
    networks:
      - net_budget_dev
    ports:
      - "${PORT}:3000"
      - 9229:9229
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DEBUG: ${DEBUG}
      SKIP_APP: ${SKIP_APP}
      FAKE_STOCK_PRICES: "true"
      PORT: 3000
      DATABASE_URL: postgres://docker:docker@db:5432/budget
      DEFAULT_PIN: 1234
  db:
    restart: always
    image: postgres:10.4
    networks:
      - net_budget_dev
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  net_budget_dev:
    driver: bridge
