/**
 * Action constants
 */

export const ERROR_OPENED = 'ERROR_OPENED';
export const ERROR_CLOSED = 'ERROR_CLOSED';
export const ERROR_REMOVED = 'ERROR_REMOVED';

export const LOGIN_FORM_INPUTTED = 'LOGIN_FORM_INPUTTED';
export const LOGIN_FORM_RESET = 'LOGIN_FORM_RESET';
export const LOGIN_FORM_SUBMITTED = 'LOGIN_FORM_SUBMITTED';
export const LOGIN_FORM_RESPONSE_GOT = 'LOGIN_FORM_RESPONSE_GOT';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const PAGE_NAVIGATED = 'PAGE_NAVIGATED';
export const KEY_PRESSED = 'KEY_PRESSED';
export const TIME_UPDATED = 'TIME_UPDATED';
export const SERVER_UPDATED = 'SERVER_UPDATED';
export const SERVER_UPDATE_RECEIVED = 'SERVER_UPDATE_RECEIVED';
export const SERVER_ADD_RECEIVED = 'SERVER_ADD_RECEIVED';

export const CONTENT_LOADED = 'CONTENT_LOADED';
export const CONTENT_REQUESTED = 'CONTENT_REQUESTED';
export const CONTENT_BLOCK_HOVERED = 'CONTENT_BLOCK_HOVERED';
export const CONTENT_BLOCKS_RECEIVED = 'CONTENT_BLOCKS_RECEIVED';

export const ANALYSIS_OPTION_CHANGED = 'ANALYSIS_OPTION_CHANGED';
export const ANALYSIS_DATA_REFRESHED = 'ANALYSIS_DATA_REFRESHED';
export const ANALYSIS_TREE_DISPLAY_TOGGLED = 'ANALYSIS_TREE_DISPLAY_TOGGLED';
export const ANALYSIS_TREE_EXPAND_TOGGLED = 'ANALYSIS_TREE_EXPAND_TOGGLED';
export const ANALYSIS_TREE_HOVERED = 'ANALYSIS_TREE_HOVERED';
export const ANALYSIS_BLOCK_CLICKED = 'ANALYSIS_BLOCK_CLICKED';

export const EDIT_ACTIVATED = 'EDIT_ACTIVATED';
export const EDIT_CHANGED = 'EDIT_CHANGED';
export const EDIT_LIST_ITEM_ADDED = 'EDIT_LIST_ITEM_ADDED';
export const EDIT_LIST_ITEM_DELETED = 'EDIT_LIST_ITEM_DELETED';
export const EDIT_SUGGESTIONS_REQUESTED = 'EDIT_SUGGESTIONS_REQUESTED';
export const EDIT_SUGGESTIONS_RECEIVED = 'EDIT_SUGGESTIONS_RECEIVED';

export const EDIT_FUND_TRANSACTIONS_CHANGED = 'EDIT_FUND_TRANSACTIONS_CHANGED';
export const EDIT_FUND_TRANSACTIONS_ADDED = 'EDIT_FUND_TRANSACTIONS_ADDED';
export const EDIT_FUND_TRANSACTIONS_REMOVED = 'EDIT_FUND_TRANSACTIONS_REMOVED';

export const FORM_EDIT_DIALOG_OPENED = 'FORM_EDIT_DIALOG_OPENED';
export const FORM_ADD_DIALOG_OPENED = 'FORM_ADD_DIALOG_OPENED';
export const FORM_DIALOG_CLOSED = 'FORM_DIALOG_CLOSED';
export const FORM_INPUT_CHANGED = 'FORM_INPUT_CHANGED';

export const GRAPH_SHOWALL_TOGGLED = 'GRAPH_SHOWALL_TOGGLED';
export const GRAPH_FUND_ITEM_TOGGLED = 'GRAPH_FUND_ITEM_TOGGLED';
export const GRAPH_FUNDS_CLICKED = 'GRAPH_FUNDS_CLICKED';
export const GRAPH_FUNDS_ZOOMED = 'GRAPH_FUNDS_ZOOMED';
export const GRAPH_FUNDS_HOVERED = 'GRAPH_FUNDS_HOVERED';
export const GRAPH_FUNDS_LINE_TOGGLED = 'GRAPH_FUNDS_LINE_TOGGLED';
export const GRAPH_FUNDS_PERIOD_CHANGED = 'GRAPH_FUNDS_PERIOD_CHANGED';
export const GRAPH_FUNDS_PERIOD_LOADED = 'GRAPH_FUNDS_PERIOD_LOADED';

export const STOCKS_LIST_REQUESTED = 'STOCKS_LIST_REQUESTED';
export const STOCKS_LIST_RECEIVED = 'STOCKS_LIST_RECEIVED';
export const STOCKS_PRICES_REQUESTED = 'STOCKS_PRICES_REQUESTED';
export const STOCKS_PRICES_RECEIVED = 'STOCKS_PRICES_RECEIVED';

