/**
 * Effect constants
 */

export const LOCAL_SETTINGS_REQUESTED = 'LOCAL_SETTINGS_REQUESTED';
export const LOGIN_FORM_SUBMIT = 'LOGIN_FORM_SUBMIT';
export const LOGIN_CREDENTIALS_SAVED = 'LOGIN_CREDENTIALS_SAVED';

export const CONTENT_REQUESTED = 'CONTENT_REQUESTED';
export const SUGGESTIONS_REQUESTED = 'SUGGESTIONS_REQUESTED';
export const BLOCKS_REQUESTED = 'BLOCKS_REQUESTED';

export const SERVER_UPDATE_REQUESTED = 'SERVER_UPDATE_REQUESTED';
export const SERVER_ADD_REQUESTED = 'SERVER_ADD_REQUESTED';
export const SERVER_MODAL_EFFECT_HANDLER = 'SERVER_MODAL_EFFECT_HANDLER';

export const ANALYSIS_DATA_REQUESTED = 'ANALYSIS_DATA_REQUESTED';
export const ANALYSIS_EXTRA_REQUESTED = 'ANALYSIS_EXTRA_REQUESTED';

export const FUNDS_PERIOD_REQUESTED = 'FUNDS_PERIOD_REQUESTED';

// TODO
export const STOCKS_LIST_REQUESTED = 'STOCKS_LIST_REQUESTED';
export const STOCKS_PRICES_REQUESTED = 'STOCKS_PRICES_REQUESTED';

