export const ERRORED = 'io/ERRORED';

export const OVERVIEW_READ = 'io/OVERVIEW_READ';

export const NET_WORTH_READ = 'io/NET_WORTH_READ';

export const NET_WORTH_CATEGORY_CREATED = 'io/NET_WORTH_CATEGORY_CREATED';
export const NET_WORTH_CATEGORY_UPDATED = 'io/NET_WORTH_CATEGORY_UPDATED';
export const NET_WORTH_CATEGORY_DELETED = 'io/NET_WORTH_CATEGORY_DELETED';

export const NET_WORTH_SUBCATEGORY_CREATED = 'io/NET_WORTH_SUBCATEGORY_CREATED';
export const NET_WORTH_SUBCATEGORY_UPDATED = 'io/NET_WORTH_SUBCATEGORY_UPDATED';
export const NET_WORTH_SUBCATEGORY_DELETED = 'io/NET_WORTH_SUBCATEGORY_DELETED';

export const NET_WORTH_ENTRY_CREATED = 'io/NET_WORTH_ENTRY_CREATED';
export const NET_WORTH_ENTRY_UPDATED = 'io/NET_WORTH_ENTRY_UPDATED';
export const NET_WORTH_ENTRY_DELETED = 'io/NET_WORTH_ENTRY_DELETED';
