export const ERRORED = 'io/ERRORED';

export const OVERVIEW_READ = 'io/OVERVIEW_READ';

export const NET_WORTH_CATEGORIES_READ = 'io/NET_WORTH_CATEGORIES_READ';
export const NET_WORTH_SUBCATEGORIES_READ = 'io/NET_WORTH_SUBCATEGORIES_READ';
export const NET_WORTH_ENTRIES_READ = 'io/NET_WORTH_ENTRIES_READ';
