export const CLIENT_CONNECTED = 'CLIENT_CONNECTED';
export const CLIENT_DISCONNECTED = 'CLIENT_DISCONNECTED';
export const QUOTES_REQUESTED = 'QUOTES_REQUESTED';
export const QUOTES_REFRESHED = 'QUOTES_REFRESHED';
export const QUOTE_API_REQUESTED = 'QUOTE_API_REQUESTED';
export const STOCK_RECEIVED = 'STOCK_RECEIVED';
export const CURRENCY_RECEIVED = 'CURRENCY_RECEIVED';
