export default {
  pio2: Math.PI / 2,

  E_NO_STORAGE: "Your browser does not support HTML5 storage, so logins won't be remembered.",

  MSG_TIME_DEBUG : 0,
  MSG_TIME_WARN  : 2000,
  MSG_TIME_ERROR : 5000,
  MSG_TIME_FATAL : 0,

  MIN_MSG_LEVEL : 1,

  PIE_LABEL_RADIUS_START: 1.1,
  PIE_LABEL_RADIUS_SCALE: 1.2,
  PIE_LABEL_INSIDE_RADIUS: 0.6,
  PIE_LABEL_SWITCH_POINT: 0.65,
  PIE_LABEL_SCALE_FACTOR_PRE: 0.4,
  PIE_LABEL_SCALE_FACTOR_POST: 1.2,
  PIE_SMALL_LABEL_OFFSET: 10,
  PIE_DEPTH: 10,

  NAV_HANDLE_EVENT: "click",

  SEARCH_SUGGESTION_THROTTLE_TIME: 250,

  ANALYSIS_VIEW_WIDTH  : 500,
  ANALYSIS_VIEW_HEIGHT : 500,

  DO_STOCKS_LIST: true,

  GRAPH_FUNDS_PIE_WIDTH: 500,
  GRAPH_FUND_ITEM_LINE_WIDTH: 2,
  GRAPH_FUND_ITEM_TENSION: 0.85,
  GRAPH_FUND_HISTORY_WIDTH: 500,
  GRAPH_FUND_HISTORY_WIDTH_NARROW: 400,
  GRAPH_FUND_HISTORY_TENSION: 0.85,
  GRAPH_FUND_HISTORY_NUM_TICKS: 10,
  GRAPH_FUND_HISTORY_LINE_WIDTH: 1,
  GRAPH_FUND_HISTORY_POINT_RADIUS: 3,

  GRAPH_BALANCE_NUM_TICKS: 5,

  GRAPH_KEY_SIZE: 12,
  GRAPH_KEY_OFFSET_X: 5,
  GRAPH_KEY_OFFSET_Y: 34,

  COLOR_GRAPH_TITLE: "#000",
  COLOR_DARK: "#333",
  COLOR_LIGHT: "#eee",
  COLOR_LIGHT_GREY: "#999",

  COLOR_PROFIT: "#0c3",
  COLOR_LOSS: "#c30",
  COLOR_PROFIT_LIGHT: "#94efa0",
  COLOR_LOSS_LIGHT: "#ffd1d1",

  COLOR_BALANCE_ACTUAL: "#039",
  COLOR_BALANCE_PREDICTED: "#f00",

  COLOR_GRAPH_FUND_ITEM: "#4286f4",

  COLOR_GRAPH_FUND_LINE: "#fffd93",
  COLOR_GRAPH_FUND_POINT: "#ff9400",

  COLOR_PIE_L1: "#f15854",
  COLOR_PIE_L2: "#decf3f",
  COLOR_PIE_L3: "#b276b2",
  COLOR_PIE_M1: "#b2912f",
  COLOR_PIE_M2: "#f17cb0",
  COLOR_PIE_M3: "#60bd68",
  COLOR_PIE_S1: "#faa43a",
  COLOR_PIE_S2: "#5da5da",

  FONT_AXIS_LABEL: "12px Arial, Helvetica, sans-serif",
  FONT_GRAPH_TITLE: "16px bold Arial, Helvetica, sans-serif",
  FONT_GRAPH_TITLE_LARGE: "18px bold Arial, Helvetica, sans-serif",
  FONT_GRAPH_KEY: "13px Arial, Helvetica, sans-serif",
  FONT_GRAPH_KEY_SMALL: "11px Arial, Helvetica, sans-serif",

  STOCKS_REFRESH_INTERVAL: 10000,
  STOCKS_LIST_WIDTH: 300
};

