export const ANALYSIS_OPTION_CHANGED = '@@analysis/OPTION_CHANGED';
export const ANALYSIS_DATA_REFRESHED = '@@analysis/DATA_REFRESHED';
export const ANALYSIS_TREE_DISPLAY_TOGGLED = '@@analysis/TREE_DISPLAY_TOGGLED';
export const ANALYSIS_TREE_HOVERED = '@@analysis/TREE_HOVERED';
export const ANALYSIS_BLOCK_CLICKED = '@@analysis/BLOCK_CLICKED';
