export const FUNDS_VIEW_SOLD_TOGGLED = '@@funds/VIEW_SOLD_TOGGLED';
export const GRAPH_FUNDS_CLICKED = '@@funds/GRAPH_CLICKED';
export const GRAPH_FUNDS_LINE_TOGGLED = '@@funds/GRAPH_LINE_TOGGLED';
export const GRAPH_FUNDS_PERIOD_CHANGED = '@@funds/GRAPH_PERIOD_CHANGED';
export const GRAPH_FUNDS_PERIOD_LOADED = '@@funds/GRAPH_PERIOD_LOADED';
