openapi: "3.0.0"
info:
  version: 4.0.0
  title: Budget
  license:
    name: MIT

servers:
  - url: http://localhost:3000/api/v4
    description: dev
  - url: https://budget.fela.space/api/v4
    description: prod

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

security:
  - BearerAuth: []

paths:
  /liveness:
    get:
      summary: Get liveness state
      responses:
        200:
          description: App is live
          content:
            application/json:
            schema:
              type: object
              properties:
                ok:
                  type: boolean
                  example: true
        500:
          description: App is not live
          content:
            application/json:
            schema:
              type: object
              properties:
                ok:
                  type: boolean
                  example: false
  /readiness:
    get:
      summary: Get readiness state
      responses:
        200:
          description: App is ready for connections
          content:
            application/json:
            schema:
              type: object
              properties:
                ok:
                  type: boolean
                  example: true
        500:
          description: App is not ready for connections
          content:
            application/json:
            schema:
              type: object
              properties:
                ok:
                  type: boolean
                  example: false

definitions:
  ErrorResponse:
    type: object
    properties:
      error:
        type: boolean
        example: true
        optional: true
      errorMessage:
        type: string
        example: An error occurred
