export const STEP_DATE = 'STEP_DATE';
export const STEP_CURRENCIES = 'STEP_CURRENCIES';
export const STEP_VALUES = 'STEP_VALUES';
export const STEP_ASSETS = 'STEP_ASSETS';
export const STEP_LIABILITIES = 'STEP_LIABILITIES';

export const steps = [STEP_DATE, STEP_CURRENCIES, STEP_ASSETS, STEP_LIABILITIES];
